version: '3'
services:
  auth-app:
    build: ./auth-service/.
    ports:
      - '7575:7575'
    depends_on:
      - postgres-auth
    restart: unless-stopped

  transfer-app:
    build: ./money-transfer/.
    ports:
      - '8080:8080'
    depends_on:
      - postgres-app
      - redis
    restart: unless-stopped

  postgres-auth:
    container_name: postgres-auth
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ./auth-service/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - '5432:5432'
    restart: unless-stopped

  postgres-app:
    container_name: postgres-app
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ./money-transfer/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - '5433:5432'
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - '6380:6380'
    restart: unless-stopped
