bind_add = ":8080"


db_host = "postgres-app"
db_port = ":54325433"
db_name = "postgres"
db_user = "postgres"
db_password = "postgres"

access_token_secret = "18DbJX9NR0WApJtB9OgmQkdlmHLwaHpK"
refresh_token_secret = "ICdzotFuzFduNeFhWvg4cieOTWyFccIr"
access_token_ttl = "1h"
refresh_token_ttl = "168h"