CREATE TABLE IF NOT EXISTS accounts (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    OwnerID BIGSERIAL NOT NULL,
    IIN VARCHAR NOT NULL,
    Amount BIGSERIAL NOT NULL,
    Registered TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    SenderID BIGSERIAL NOT NULL,
    ReceiverID BIGSERIAL NOT NULL,
    Amount BIGSERIAL NOT NULL,
    Date TIMESTAMP NOT NULL,
    FOREIGN KEY (SenderID) REFERENCES accounts (ID),
    FOREIGN KEY (ReceiverID) REFERENCES accounts (ID)
);