bind_add = ":7575"

cache_host = "redis"
cache_password = ""
cache_add = ":6380"


access_token_secret = "18DbJX9NR0WApJtB9OgmQkdlmHLwaHpK"
refresh_token_secret = "ICdzotFuzFduNeFhWvg4cieOTWyFccIr"
access_token_ttl = "1h"
refresh_token_ttl = "168h"

db_host = "postgres-auth"
db_port = ":5432"
db_name = "postgres"
db_user = "postgres"
db_password = "postgres"